from datetime import datetime, timedelta, timezone

from pymongo.errors import PyMongoError
from app.database import database

NOW = datetime.now(timezone.utc)

USER_PROFILES = [{'department': 'Computer Science',
  'email': 'aditya.verma@orbit.example',
  'firstName': 'Aditya',
  'interests': ['Robotics', 'Coding'],
  'lastName': 'Verma',
  'role': 'organizer'},
 {'department': 'Aerospace Engineering',
  'email': 'beatrice.moreau@orbit.example',
  'firstName': 'Beatrice',
  'interests': ['Space', 'Engineering'],
  'lastName': 'Moreau',
  'role': 'staff'},
 {'department': 'Applied Mathematics',
  'email': 'cedric.lambert@orbit.example',
  'firstName': 'Cedric',
  'interests': ['Statistics', 'Research'],
  'lastName': 'Lambert',
  'role': 'student'},
 {'department': 'Physics',
  'email': 'dalia.hassan@orbit.example',
  'firstName': 'Dalia',
  'interests': ['Astronomy', 'Optics'],
  'lastName': 'Hassan',
  'role': 'student'},
 {'department': 'Biotechnology',
  'email': 'emilio.reyes@orbit.example',
  'firstName': 'Emilio',
  'interests': ['Biology', 'Discovery'],
  'lastName': 'Reyes',
  'role': 'student'},
 {'department': 'Business Analytics',
  'email': 'fatima.rahman@orbit.example',
  'firstName': 'Fatima',
  'interests': ['Strategy', 'Data'],
  'lastName': 'Rahman',
  'role': 'student'},
 {'department': 'Computer Science',
  'email': 'gabriel.martin@orbit.example',
  'firstName': 'Gabriel',
  'interests': ['Robotics', 'Coding'],
  'lastName': 'Martin',
  'role': 'organizer'},
 {'department': 'Aerospace Engineering',
  'email': 'helena.duarte@orbit.example',
  'firstName': 'Helena',
  'interests': ['Space', 'Engineering'],
  'lastName': 'Duarte',
  'role': 'staff'},
 {'department': 'Applied Mathematics',
  'email': 'idris.bello@orbit.example',
  'firstName': 'Idris',
  'interests': ['Statistics', 'Research'],
  'lastName': 'Bello',
  'role': 'student'},
 {'department': 'Physics',
  'email': 'juliette.bernard@orbit.example',
  'firstName': 'Juliette',
  'interests': ['Astronomy', 'Optics'],
  'lastName': 'Bernard',
  'role': 'student'},
 {'department': 'Biotechnology',
  'email': 'kiran.desai@orbit.example',
  'firstName': 'Kiran',
  'interests': ['Biology', 'Discovery'],
  'lastName': 'Desai',
  'role': 'student'},
 {'department': 'Business Analytics',
  'email': 'lucia.navarro@orbit.example',
  'firstName': 'Lucia',
  'interests': ['Strategy', 'Data'],
  'lastName': 'Navarro',
  'role': 'student'},
 {'department': 'Computer Science',
  'email': 'malik.diallo@orbit.example',
  'firstName': 'Malik',
  'interests': ['Robotics', 'Coding'],
  'lastName': 'Diallo',
  'role': 'organizer'},
 {'department': 'Aerospace Engineering',
  'email': 'nadine.weber@orbit.example',
  'firstName': 'Nadine',
  'interests': ['Space', 'Engineering'],
  'lastName': 'Weber',
  'role': 'staff'},
 {'department': 'Applied Mathematics',
  'email': 'olivier.petit@orbit.example',
  'firstName': 'Olivier',
  'interests': ['Statistics', 'Research'],
  'lastName': 'Petit',
  'role': 'student'},
 {'department': 'Physics',
  'email': 'priya.menon@orbit.example',
  'firstName': 'Priya',
  'interests': ['Astronomy', 'Optics'],
  'lastName': 'Menon',
  'role': 'student'},
 {'department': 'Biotechnology',
  'email': 'quentin.dubois@orbit.example',
  'firstName': 'Quentin',
  'interests': ['Biology', 'Discovery'],
  'lastName': 'Dubois',
  'role': 'student'},
 {'department': 'Business Analytics',
  'email': 'rania.saleh@orbit.example',
  'firstName': 'Rania',
  'interests': ['Strategy', 'Data'],
  'lastName': 'Saleh',
  'role': 'student'},
 {'department': 'Computer Science',
  'email': 'sebastian.klein@orbit.example',
  'firstName': 'Sebastian',
  'interests': ['Robotics', 'Coding'],
  'lastName': 'Klein',
  'role': 'organizer'},
 {'department': 'Aerospace Engineering',
  'email': 'tara.joshi@orbit.example',
  'firstName': 'Tara',
  'interests': ['Space', 'Engineering'],
  'lastName': 'Joshi',
  'role': 'staff'},
 {'department': 'Applied Mathematics',
  'email': 'ugo.bianchi@orbit.example',
  'firstName': 'Ugo',
  'interests': ['Statistics', 'Research'],
  'lastName': 'Bianchi',
  'role': 'student'},
 {'department': 'Physics',
  'email': 'valentina.cruz@orbit.example',
  'firstName': 'Valentina',
  'interests': ['Astronomy', 'Optics'],
  'lastName': 'Cruz',
  'role': 'student'},
 {'department': 'Biotechnology',
  'email': 'wassim.khalil@orbit.example',
  'firstName': 'Wassim',
  'interests': ['Biology', 'Discovery'],
  'lastName': 'Khalil',
  'role': 'student'},
 {'department': 'Business Analytics',
  'email': 'xenia.popova@orbit.example',
  'firstName': 'Xenia',
  'interests': ['Strategy', 'Data'],
  'lastName': 'Popova',
  'role': 'student'},
 {'department': 'Computer Science',
  'email': 'yusuf.demir@orbit.example',
  'firstName': 'Yusuf',
  'interests': ['Robotics', 'Coding'],
  'lastName': 'Demir',
  'role': 'organizer'},
 {'department': 'Aerospace Engineering',
  'email': 'zoe.mercier@orbit.example',
  'firstName': 'Zoe',
  'interests': ['Space', 'Engineering'],
  'lastName': 'Mercier',
  'role': 'staff'},
 {'department': 'Applied Mathematics',
  'email': 'alec.turner@orbit.example',
  'firstName': 'Alec',
  'interests': ['Statistics', 'Research'],
  'lastName': 'Turner',
  'role': 'student'},
 {'department': 'Physics',
  'email': 'bianca.marino@orbit.example',
  'firstName': 'Bianca',
  'interests': ['Astronomy', 'Optics'],
  'lastName': 'Marino',
  'role': 'student'},
 {'department': 'Biotechnology',
  'email': 'cyrus.patel@orbit.example',
  'firstName': 'Cyrus',
  'interests': ['Biology', 'Discovery'],
  'lastName': 'Patel',
  'role': 'student'},
 {'department': 'Business Analytics',
  'email': 'daphne.scott@orbit.example',
  'firstName': 'Daphne',
  'interests': ['Strategy', 'Data'],
  'lastName': 'Scott',
  'role': 'student'},
 {'department': 'Computer Science',
  'email': 'esteban.vega@orbit.example',
  'firstName': 'Esteban',
  'interests': ['Robotics', 'Coding'],
  'lastName': 'Vega',
  'role': 'organizer'},
 {'department': 'Aerospace Engineering',
  'email': 'farah.aziz@orbit.example',
  'firstName': 'Farah',
  'interests': ['Space', 'Engineering'],
  'lastName': 'Aziz',
  'role': 'staff'},
 {'department': 'Applied Mathematics',
  'email': 'giselle.fontaine@orbit.example',
  'firstName': 'Giselle',
  'interests': ['Statistics', 'Research'],
  'lastName': 'Fontaine',
  'role': 'student'},
 {'department': 'Physics',
  'email': 'hugo.leclerc@orbit.example',
  'firstName': 'Hugo',
  'interests': ['Astronomy', 'Optics'],
  'lastName': 'Leclerc',
  'role': 'student'},
 {'department': 'Biotechnology',
  'email': 'imran.sheikh@orbit.example',
  'firstName': 'Imran',
  'interests': ['Biology', 'Discovery'],
  'lastName': 'Sheikh',
  'role': 'student'},
 {'department': 'Business Analytics',
  'email': 'josephine.roy@orbit.example',
  'firstName': 'Josephine',
  'interests': ['Strategy', 'Data'],
  'lastName': 'Roy',
  'role': 'student'},
 {'department': 'Computer Science',
  'email': 'kabir.sethi@orbit.example',
  'firstName': 'Kabir',
  'interests': ['Robotics', 'Coding'],
  'lastName': 'Sethi',
  'role': 'organizer'},
 {'department': 'Aerospace Engineering',
  'email': 'leila.amrani@orbit.example',
  'firstName': 'Leila',
  'interests': ['Space', 'Engineering'],
  'lastName': 'Amrani',
  'role': 'staff'},
 {'department': 'Applied Mathematics',
  'email': 'marcus.evans@orbit.example',
  'firstName': 'Marcus',
  'interests': ['Statistics', 'Research'],
  'lastName': 'Evans',
  'role': 'student'},
 {'department': 'Physics',
  'email': 'natalie.brooks@orbit.example',
  'firstName': 'Natalie',
  'interests': ['Astronomy', 'Optics'],
  'lastName': 'Brooks',
  'role': 'student'},
 {'department': 'Biotechnology',
  'email': 'pascal.girard@orbit.example',
  'firstName': 'Pascal',
  'interests': ['Biology', 'Discovery'],
  'lastName': 'Girard',
  'role': 'student'},
 {'department': 'Business Analytics',
  'email': 'rhea.iyer@orbit.example',
  'firstName': 'Rhea',
  'interests': ['Strategy', 'Data'],
  'lastName': 'Iyer',
  'role': 'student'}]

USERS = [dict(profile, createdAt=NOW - timedelta(days=150)) for profile in USER_PROFILES]

EVENT_SPECS = [('Satellite Signal Sprint',
  'Decode a recorded satellite transmission and plot its ground track. Teams receive a signal '
  'workbook and compare their recovered telemetry.',
  'Space',
  ['Space', 'Signals'],
  0,
  -63,
  19,
  'Nova Research Centre',
  'Suite 201',
  0,
  8),
 ('Robot Maze Trials',
  'Program a wheeled robot to navigate a timed maze. Test distance sensors and tune your route '
  'before the final challenge.',
  'Robotics',
  ['Robotics', 'Automation'],
  6,
  -57,
  25,
  'Kepler Hall',
  'Suite 202',
  5,
  15),
 ('Protein Folding Playground',
  'Build physical protein models and compare them with computer predictions. Explore how shape '
  'influences biological function.',
  'Biotech',
  ['Biotech', 'Proteins'],
  12,
  -51,
  23,
  'Vector Labs',
  'Suite 203',
  10,
  11),
 ('Numbers Behind the Match',
  'Analyse a sports dataset and present a tactical recommendation. Bring a laptop; starter '
  'notebooks are supplied.',
  'Data',
  ['Data', 'Statistics'],
  18,
  -45,
  22,
  'Photon Pavilion',
  'Suite 204',
  15,
  22),
 ('Optics After Hours',
  'Assemble a small optical bench and investigate lenses, diffraction and colour. Work in pairs '
  'with supervised equipment.',
  'Physics',
  ['Physics', 'Optics'],
  24,
  -39,
  17,
  'Helix Institute',
  'Suite 205',
  20,
  9),
 ('Startup Pricing Clinic',
  'Test subscription pricing with a fictional product case. Build a unit economics model and '
  'defend your assumptions.',
  'Enterprise',
  ['Enterprise', 'Strategy'],
  30,
  -33,
  31,
  'Launchpad Building',
  'Suite 206',
  25,
  17),
 ('Cloud Systems Flight Deck',
  'Deploy a small service and trace a request across its components. Practise reading logs and '
  'diagnosing a simulated outage.',
  'Computing',
  ['Computing', 'Cloud'],
  0,
  -27,
  26,
  'Nova Research Centre',
  'Suite 207',
  30,
  13),
 ('Lunar Habitat Challenge',
  'Design a compact lunar living module with a strict energy budget. Present your tradeoffs using '
  'a scale floor plan.',
  'Space',
  ['Space', 'Habitats'],
  6,
  -21,
  30,
  'Kepler Hall',
  'Suite 208',
  35,
  18),
 ('Machine Vision Lab',
  'Train a tiny image classifier and test it under changing lighting. Compare errors and document '
  'limits of the model.',
  'Robotics',
  ['Robotics', 'Vision'],
  12,
  -15,
  24,
  'Vector Labs',
  'Suite 209',
  4,
  24),
 ('Microbes Under the Lens',
  'Observe prepared microscope slides and learn to record reproducible observations. Lab coats and '
  'equipment are provided.',
  'Biotech',
  ['Biotech', 'Microscopy'],
  18,
  -9,
  21,
  'Photon Pavilion',
  'Suite 210',
  9,
  7),
 ('Forecasting the Unexpected',
  'Compare forecasting methods on changing demand data. Explain uncertainty through a short visual '
  'briefing.',
  'Data',
  ['Data', 'Forecasting'],
  24,
  -3,
  35,
  'Helix Institute',
  'Suite 211',
  14,
  21),
 ('Quantum Puzzle Room',
  'Solve collaborative puzzles about probability and quantum measurement. No advanced mathematics '
  'is required.',
  'Physics',
  ['Physics', 'Quantum'],
  30,
  3,
  28,
  'Launchpad Building',
  'Suite 212',
  19,
  16),
 ('Founder Negotiation Arena',
  'Role-play a partnership negotiation with limited resources. Debrief the decisions that changed '
  'the outcome.',
  'Enterprise',
  ['Enterprise', 'Negotiation'],
  0,
  7,
  29,
  'Nova Research Centre',
  'Suite 213',
  24,
  12),
 ('Cyber Defence Tabletop',
  'Investigate a fictional security incident using supplied logs. Produce an incident timeline and '
  'recovery checklist.',
  'Computing',
  ['Computing', 'Security'],
  6,
  11,
  33,
  'Kepler Hall',
  'Suite 214',
  29,
  20),
 ('Mars Rover Mission',
  'Plan a rover route across a simulated terrain map. Balance battery life, science targets and '
  'communication windows.',
  'Space',
  ['Space', 'Exploration'],
  12,
  15,
  27,
  'Vector Labs',
  'Suite 215',
  34,
  14),
 ('Drone Control Simulator',
  'Tune a virtual drone controller and measure its response. All flying takes place inside a '
  'simulator.',
  'Robotics',
  ['Robotics', 'Control'],
  18,
  19,
  25,
  'Photon Pavilion',
  'Suite 216',
  3,
  25),
 ('DNA Data Detectives',
  'Explore a public teaching sequence dataset and identify simple patterns. Learn the difference '
  'between a match and an interpretation.',
  'Biotech',
  ['Biotech', 'Genomics'],
  24,
  23,
  24,
  'Helix Institute',
  'Suite 217',
  8,
  10),
 ('Visual Analytics Jam',
  'Turn a messy dataset into a clear interactive story. Review chart choices with peers and '
  'publish a local prototype.',
  'Data',
  ['Data', 'Visualisation'],
  30,
  27,
  32,
  'Launchpad Building',
  'Suite 218',
  13,
  19),
 ('Particle Track Studio',
  'Reconstruct particle paths from sample detector images. Compare measurements and discuss '
  'experimental uncertainty.',
  'Physics',
  ['Physics', 'Particles'],
  0,
  31,
  37,
  'Nova Research Centre',
  'Suite 219',
  18,
  23),
 ('Product Experiment Lab',
  'Design an experiment for a fictional campus service. Define a metric, sample plan and decision '
  'rule.',
  'Enterprise',
  ['Enterprise', 'Experiments'],
  6,
  35,
  18,
  'Kepler Hall',
  'Suite 220',
  23,
  6),
 ('Open Source Launchpad',
  'Practise the contribution workflow in a local training repository. Review a patch and write '
  'useful feedback.',
  'Computing',
  ['Computing', 'Collaboration'],
  12,
  39,
  40,
  'Vector Labs',
  'Suite 221',
  28,
  27),
 ('Telescope Navigation Night',
  'Learn star charts and plan an observing session with the astronomy society. Indoor alternatives '
  'are provided for cloudy skies.',
  'Space',
  ['Space', 'Astronomy'],
  18,
  43,
  34,
  'Photon Pavilion',
  'Suite 222',
  33,
  18),
 ('Human Robot Interface',
  'Prototype a control panel for an assistive robot. Test the interface with another team and '
  'refine the interaction.',
  'Robotics',
  ['Robotics', 'Interfaces'],
  24,
  47,
  30,
  'Helix Institute',
  'Suite 223',
  2,
  15),
 ('Bio Materials Showcase',
  'Compare demonstration materials made from renewable feedstocks. Record their properties and '
  'discuss potential applications.',
  'Biotech',
  ['Biotech', 'Materials'],
  30,
  51,
  26,
  'Launchpad Building',
  'Suite 224',
  7,
  12),
 ('Decision Science Tournament',
  'Solve competing allocation problems using a shared dataset. Explain how constraints change the '
  'best solution.',
  'Data',
  ['Data', 'Optimisation'],
  0,
  55,
  39,
  'Nova Research Centre',
  'Suite 225',
  12,
  26),
 ('Energy Storage Bench',
  'Compare battery models using supplied measurement data. Calculate efficiency and prepare a '
  'short lab report.',
  'Physics',
  ['Physics', 'Energy'],
  6,
  59,
  22,
  'Kepler Hall',
  'Suite 226',
  17,
  9),
 ('Venture Demo Exchange',
  'Present a three-minute product concept to a peer panel. Receive structured feedback on the '
  'problem, customer and evidence.',
  'Enterprise',
  ['Enterprise', 'Pitching'],
  12,
  63,
  42,
  'Vector Labs',
  'Suite 227',
  22,
  28),
 ('Distributed Systems Sandbox',
  'Simulate message delays and node failures in a local cluster. Observe consistency tradeoffs '
  'using a guided exercise.',
  'Computing',
  ['Computing', 'Systems'],
  18,
  67,
  36,
  'Photon Pavilion',
  'Suite 228',
  27,
  0),
 ('Rocket Trajectory Workshop',
  'Calculate a simulated launch trajectory with changing mass. Compare numerical results with a '
  'simplified model.',
  'Space',
  ['Space', 'Simulation'],
  24,
  71,
  45,
  'Helix Institute',
  'Suite 229',
  32,
  0),
 ('Autonomous Futures Forum',
  'Discuss student projects in automation and responsible engineering. End with a collaborative '
  'plan for next term.',
  'Robotics',
  ['Robotics', 'Ethics'],
  30,
  75,
  50,
  'Launchpad Building',
  'Suite 230',
  1,
  0)]

def build_registration(user_ids, user_index, start_date):
    return {
        "userId": user_ids[user_index],
        "registeredAt": min(NOW, start_date) - timedelta(days=3 + user_index % 10),
        "status": "confirmed",
    }


def build_events(user_ids):
    events = []

    for index, spec in enumerate(EVENT_SPECS):
        (
            title,
            description,
            category,
            tags,
            organizer_index,
            day_offset,
            capacity,
            building,
            room,
            registration_start,
            registration_count,
        ) = spec

        start_date = (NOW + timedelta(days=day_offset)).replace(hour=10 + index % 8, minute=30 if index % 2 else 0, second=0, microsecond=0)
        end_date = start_date + timedelta(minutes=[90, 120, 150, 180][index % 4])

        registrations = []
        used_user_indexes = set()

        for position in range(registration_count):
            user_index = (registration_start + position) % (len(user_ids) - 6)

            while (
                user_index == organizer_index
                or user_index in used_user_indexes
            ):
                user_index = (user_index + 1) % (len(user_ids) - 6)

            used_user_indexes.add(user_index)

            registrations.append(
                build_registration(user_ids, user_index, start_date)
            )

        events.append(
            {
                "title": title,
                "description": description,
                "category": category,
                "tags": tags,
                "startDate": start_date,
                "endDate": end_date,
                "capacity": capacity,
                "location": {
                    "building": building,
                    "room": room,
                    "address": "Orbit Science Campus, Toulouse, France",
                },
                "organizerId": user_ids[organizer_index],
                "registrations": registrations,
                "createdAt": min(NOW, start_date) - timedelta(days=45),
                "updatedAt": NOW,
            }
        )

    return events


def seed_database():
    try:
        database.client.admin.command("ping")
        print("Connected to MongoDB.")

        # Reset only the two project collections.
        database.events.delete_many({})
        database.users.delete_many({})

        user_result = database.users.insert_many(USERS)
        user_ids = user_result.inserted_ids

        events = build_events(user_ids)
        event_result = database.events.insert_many(events)

        registration_count = sum(
            len(event["registrations"]) for event in events
        )

        print(f"Inserted {len(user_ids)} users.")
        print(f"Inserted {len(event_result.inserted_ids)} events.")
        print(f"Inserted {registration_count} embedded registrations.")
        print("Database seeded successfully.")

    except PyMongoError as error:
        print(f"Database seeding failed: {error}")
        raise

if __name__ == "__main__":
    seed_database()
